### PR TITLE
Add GCS Stage

### PR DESCRIPTION
**Pull request by yakkomajuri**
This was forked off of #5.

### CODE REVIEW

**Comment by yakkomajuri** [comment]
Made it easier to test this one - see if working on Cloud by going to the project "HogFlix Demo App" on our org. You can also check out the `APP_TEST` table (`"DEMO_DB"."PUBLIC"."APP_TEST"`) in Snowflake to confirm it works nicely

**Comment by Twixes** [comment]
I think every file has a merge conflict now. 😅

**Comment by yakkomajuri** [comment]
Yeah definitely didn't play this out perfectly

**Comment by yakkomajuri** [comment]
Closing in favor of #7

**Pull request closed without merging**
