### PR TITLE
Don't error out when bucket path doesn't exist

### PR DESCRIPTION
**Pull request by neilkakkar**
Leads to error like: https://posthogusers.slack.com/archives/C01FKPGG5U6/p1630509438020300?thread_ts=1627566038.204900&cid=C01FKPGG5U6

### CODE REVIEW

**Comment by yakkomajuri** [comment]
When does this happen? I mean ofc someone can hit the API endpoint themselves but `bucketPath` has a default value as per `plugin.json` so it should always exist

**Comment by neilkakkar** [comment]
Oh, good point, didn't realise there was a default in plugin.json 🤦‍♂️ . Let me confirm how this happens!

**Comment by yakkomajuri** [comment]
Should we close this?

**Comment by neilkakkar** [comment]
Ah, apologies didn't update here: I suspect this happened on upgrading plugin from an old version to a new one. If that is indeed the issue, this PR isn't the way to solve it, so closing.

**Pull request closed without merging**
